project: 
  - packagename: MyAsset
    source: C:\unity\projects\MyAsset\Assets\MyAssetFiles
    destination: E:\_unity\_projects\MyAsset\OutputFiles
    rootdirectory: Assets/MyAssetFiles
    ignoredextensions: []
    ignoredfolders: []
